[colors.normal]
black = "#1f1f1f"
blue = "#2a84d2"
cyan = "#1081d6"
green = "#2dc55e"
magenta = "#4e5ab7"
red = "#f81118"
white = "#d6dbe5"
yellow = "#ecba0f"

[colors.primary]
background = "#131313"
foreground = "#d6dbe5"

[font]
size = 12

[font.normal]
family = "inconsolata"
style = "Regular"

[window]
opacity = 0.9
