#!/bin/bash
$(sleep 15 && pgrep i3lock && xset dpms force off) &

#i3lock -n -t -i $HOME/.config/i3lock/lwall.jpg \
#    --insidecolor=373445ff --ringcolor=ffffffff --line-uses-inside \
#    --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
#    --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
#    --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+86:y+1003" \
#    --radius=15 --veriftext="" --wrongtext=""

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ff00ffcc'  # default
T='#ee00eeee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$W       \
--bshl-color=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--time-str="%H:%M:%S"  \
--date-str="%A, %m %Y" \
--keylayout 2         \
--verif-text="annnnd..." \
--wrong-text="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc

